apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: otel-demo-server
  name: otel-demo-server
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: otel-demo-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: otel-demo-worker
  name: otel-demo-worker
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: otel-demo-worker
  type: ClusterIP
